### ISSUE TITLE
wiki location

### ISSUE THREAD

**Issue by hypervillain** [Chysn/O_C-HemisphereSuite#100]
Hey 👋

I'd like to get the wiki as PDF but I haven't been able to locate the `.wiki` folder in the project or any MD file that looks like documentation. Can you point me toward the right place for this?

Thanks!

**Comment by Chysn** [comment]
It's under the Wiki tab on GitHub. Scroll down, and on the right side you'll see a URL to clone it locally.

For future reference, an issue tracking system isn't the best place for questions.

Cheers,
Jason
