### ISSUE TITLE
Feature request: Gate <=> Trigger Converter

### ISSUE THREAD

**Issue by Duomaki** [Chysn/O_C-HemisphereSuite#101]
I was curious whether Hemispheres currently has Gate-to-Trigger conversion functionality (and vice versa)—perhaps I'm missing something? In any case, something akin to After Later Audio's "G&T" could be really handy (https://www.modulargrid.net/e/after-later-audio-g-t).

I'm really enjoying Hemispheres BTW—thank you!

**Comment by Chysn** [comment]
Hi there. This is a bug-reporting system. If you have general questions, please bring them to one of the Hemisphere Suite forums on ModWiggler or Lines.

I don't think there's currently a way to do quite what G&T does, and there's no room in the application to add new applets. I suppose the closest thing would be the AD envelope generator, which you can use to generate a short trigger given a gate. It'll also generate a trigger at end of cycle, but this won't always correspond to gate release.
