### ISSUE TITLE
HemisphereSuite: Too Large! in Teensy

### ISSUE THREAD

**Issue by jussilampela** [Chysn/O_C-HemisphereSuite#103]
Hi,

just tried installing Teensy loader + the latest Hemisphere release to replace my standard ornament_crime version. I get the notice that the hex-file is too large. This is both on a windows machine, and on a OS X laptop. Any hints what I'm doing wrong?

thanks!

best,

Jussi L.

**Comment by benirose** [comment]
Scroll down to "method A" and follow the steps, there are details for uploading a separate HEX file if you run into this issue (second to last bullet point). I also ran into this issue the first time I loaded Hemispheres on and following these steps fixed it!

**Comment by jussilampela** [comment]
thanks, actually turned out to be a cable issue, as many have pointed out. Changed a cable and all was fine!

Thanks anyway, best,

Jussi L.
