### ISSUE TITLE
Power usage

### ISSUE THREAD

**Issue by joesh1** [Chysn/O_C-HemisphereSuite#109]
Hi, this isn't so much of an issue, more a request about the power usage of O&C and in particular the Hemisphere suite. After installing Hemisphere I've started to have a few power drop outs in my rack, and so I wonder if you could tell me about the power usage of O&C with Hemisphere? 
 
In reality, I suspect the problem is probably an underpowered rack, but just to confirm this I'd be interested if you could tell me if Hemisphere needs significantly more power than the original firmware?    

Thanks in advance.

**Comment by Chysn** [comment]
Hemisphere Suite runs the processor at the same clock speed as Ornament and Crime, so I don't think it would be the source of your dropouts.
