### ISSUE TITLE
"A"SR Freeze when scrolling past USER1

### ISSUE THREAD

**Issue by adrianfon9** [Chysn/O_C-HemisphereSuite#11]
In 1.5A, when selecting a scale in the "A"SR widget further to the left of USER 1, O+c will lock up. It will also freeze past scale "B-Pl" if scrolled to the right. I am assuming this is the same issue.

**Comment by Chysn** [comment]
Thanks for reporting this on GitHub! The fix will be in the 1.6 hex file, to be released this Friday, 10/26.
