### ISSUE TITLE
scale duet doesn't work in flipped firmware

### ISSUE THREAD

**Issue by risro** [Chysn/O_C-HemisphereSuite#112]
It seems like the scale duet doesn't work with the flipped firmware. normal firmware works just fine, but if I use the flipped one it doesn't do anything!

**Comment by Chysn** [comment]
I was able to confirm that both Scale Duet and Dual Quantizer work as expected with the Flip 180 version of 1.99Repeating. Double-check your patching, noting that Scale Duet has only one CV input and one CV output, and that it requires a clock input. Note that all three of these will use the left-hand jacks from the point of view of a flipped module.

**Comment by risro** [comment]
sorry you are correct. I didn't realize that I needed to use the left handed jacks (I'm sure I tried that at some point, but now atleast it seams to work just fine?) thank you  a lot!
