### ISSUE TITLE
Add TB3-PO App from Logarhythm1

### ISSUE THREAD

**Issue by cryptix** [Chysn/O_C-HemisphereSuite#116]
This fork has a very nice sequencer: https://github.com/Logarhythm1/O_C-HemisphereSuite/blob/logarhythm-branch/software/o_c_REV/HEM_TB3PO.ino

I feel capable to do this from a coding standpoint but I'm having trouble to get the old Arduino/Teensy toolchain to work on my macbook...

**Comment by Chysn** [comment]
Cannot move TB3PO to this codebase, no room.

**Comment by cryptix** [comment]
Understood, thanks.

Do you have a suggestion what Linux distro to use to get the toolchain running?

**Comment by Chysn** [comment]
> Do you have a suggestion what Linux distro to use to get the toolchain
running?

I've always used macOS, but everything pretty much stopped working with
Montery.

You should be able to use any up-to-date Linux distro, as long as you can
run the 1.8.1 Arduino IDE.

--jason

**Comment by cryptix** [comment]
fwiw, if somebody else finds this, I removed captain midi and pong over [here](https://github.com/cryptix/O_C-HemisphereSuite/tree/tb3po) which made enough space for it.

(the supplied image from logarithm doesn't work correctly with the VOR adjustments)
