### ISSUE TITLE
c_cpp_properties file for vscode 

### ISSUE THREAD

**Issue by Spyes** [Chysn/O_C-HemisphereSuite#117]
I want to do some Hemisphere hacking in VS Code, I build the project via Arduino IDE but it's more comforable for me to edit in VS, however it's complaining about a whole bunch of standard stuff (for example, `int32_t` being undefined) and a lot of the default includes aren't being parsed properly? In any case, does anyone have a working c_cpp_properties file to share? Thank you!

**Comment by Chysn** [comment]
This doesn't really belong in Issues, it's more of a question for forums. If you don't mind, I'm closing it without action.
