### ISSUE TITLE
Hex file for the VOR branch

### ISSUE THREAD

**Issue by m9dfukc** [Chysn/O_C-HemisphereSuite#119]
Any chance that you also add the binary for the VOR branch to your release page? Plum Audio lacks the latest VOR supported version on their download site. 

Unfortunately I am on MacOs Ventura and the software (TeensyDuino) to compile this myself is not supported on my OS anymore.

**Comment by Chysn** [comment]
I’m in the same boat, on a new macOS and out of the Hemisphere compiling business. Sorry!--jasonOn Feb 4, 2023, at 10:37 AM, Andreas Schmelas ***@***.***> wrote:﻿
Any chance that you also add the binary for the VOR branch to your release page? Plum Audio lacks the latest VOR supported version on their download site.
Unfortunately I am on MacOs Ventura and the software (TeensyDuino) to compile this myself is not supported on my OS anymore.

**Comment by Chysn** [comment]
Closed as non-defect
