### ISSUE TITLE
Calculate App - Requires 2 separate clock signals for Random

### ISSUE THREAD

**Issue by snydoodlsh** [Chysn/O_C-HemisphereSuite#124]
I'm using a Plum Audio O&C X. 1.8A.

I've been trying to use the "Random" setting on the calculate app. It would be nice when using 2 random generators, the 2nd one just automatically adopts the clock of the 1st one. Maybe you could update the programming to automatically adopt the clock / trigger of the 1st one (normalized to the 1st trigger) and if there is a need to create a different or have a different trigger, it breaks the normalization at trigger 2. Otherwise, I have to essentially split my signal into 2x in order to get 2 different random outputs. It seems unnecessary. This requires another module or a signal splitter and I would expect this app to be smarter and just adopt the 1st trigger signal until the user shows intent for a 2nd one / different one.

**Comment by Chysn** [comment]
See my note on your other issue. But also, I don’t think using a stackable is much of a hardship :)
