### ISSUE TITLE
Hemispheres Trigger On Quantize Functionality

### ISSUE THREAD

**Issue by ianjhoffman** [Chysn/O_C-HemisphereSuite#125]
Does hemispheres have the ability to just run a 1-channel Meta-Q on one of the sides? I sometimes really enjoy having a gate output from quantizers when their value changes.

**Comment by Chysn** [comment]
This channel is for bug reports, so I'm closing this issue. All functionality is documented in the Wiki. https://github.com/Chysn/O_C-HemisphereSuite/wiki, or post operational questions at ModWiggler. I do not know what "Meta-Q" is, but if it's an Ornament and Crime app, it's not here.
