### ISSUE TITLE
1.6b (Flipped Screen) CCW increment instead of decrement?

### ISSUE THREAD

**Issue by adrianfon9** [Chysn/O_C-HemisphereSuite#14]
Flipped screen firmware increments the wrong way 

e.g. Enigma JR. A-1 => [CCW turn] => A-2

e.g. Applet screen ADSR EG => [CW turn] => Voltage

**Comment by Chysn** [comment]
Encoder direction is a configuration option. Please see

http://ornament-and-cri.me/calibration/
