### ISSUE TITLE
1.6b (Flipped Screen) Trending Not working?

### ISSUE THREAD

**Issue by adrianfon9** [Chysn/O_C-HemisphereSuite#19]
Hi Chysn, 

Trending does not detect anything but a "Steady" state in cv A B C or D throughout the range of sensitivity.

Thanks again for the quick response and sorry for spamming issues especially if they are all related to the same bug.

**Comment by Chysn** [comment]
I'm unable to reproduce this issue in the flipped screen codebase. Can you verify that you're using the CV inputs and not the digital inputs?

**Comment by adrianfon9** [comment]
Fixed on reboot. I apologize.

**Comment by adrianfon9** [comment]
As an aside,

Is trending supposed to work with only 1 CV connected? I can only get either rising or falling based on if i plug cv into its corresponding input.

e.g. signal into cv 1; a:“rising” b:”falling” => trig A, no trig B
e.g. signal into cv 2; a:”rising” b: “falling” => no trig A, trig B

Adrian

**Comment by Chysn** [comment]
No worries, thanks for helping me out!

**Comment by Chysn** [comment]
Trending is now a dual applet as of 1.6. Both channels are independent. I’ll make sure to update the wiki!
