### ISSUE TITLE
CVRecorder provides VMax when recording 0V or less

### ISSUE THREAD

**Issue by senortorpedo** [Chysn/O_C-HemisphereSuite#2]
Hemisphere Suite 1.3, CV Recorder loaded on right side: Maths Channel 2 output patched into CV in, O_C output patched into V/Oct of uBraids. When getting close to 0V or below, the pitch output jumps up. It is hard to adjust the Maths channel to level which is low enough to have O_C send about 0V.
Proposal: Have CV recorder clip to 0V when input is 0V or less, or - even better - also record and put out negative values, when seen on the input side. Can teensy do that? Don't know...
Thanks for the great stuff anyway!

**Comment by Chysn** [comment]
Thanks for the report! I'll have a fix out shortly.
