### ISSUE TITLE
Clock div - Right Hemisphere

### ISSUE THREAD

**Issue by kurtjoy** [Chysn/O_C-HemisphereSuite#22]
Doesnt seem to work or works erratically in left hemi (flipped and unflipped) using the 1.6C hexes.

**Comment by Chysn** [comment]
Hey! I'm unable to reproduce this. ClockDiv seems to function correctly in both hemispheres on all outputs. Are there any specific division or multiplication values you're having trouble with? Can you please provide detailed steps to reproduce, and clarify what you man by "erratically?"

**Comment by kurtjoy** [comment]
HI. Turns out it was a hardware problem with a leg on the teensy.

**Comment by Chysn** [comment]
Ok, thanks for letting me know! —jason
