### ISSUE TITLE
Default starting app

### ISSUE THREAD

**Issue by kurtjoy** [Chysn/O_C-HemisphereSuite#24]
Is the a way to set an app to be the default starting app on a hemisphere? I always use Clock Div on the left hemisphere, so it would be great for that app to be the default on power up for that  #side.

**Comment by adrianfon9** [comment]
click the right encoder [goes to top most app select], then hold the right encoder [screen will have an expanding white box] it will save the entire state.

**Comment by kurtjoy** [comment]
Awesome. Figured it was there somewhere!

**Comment by Chysn** [comment]
Note that the above procedure will save the state _and_ initiate a system exclusive dump of the app's state, so you can also use a computer to save and restore.
