### ISSUE TITLE
1.7 Carpeggio Trigger Issue

### ISSUE THREAD

**Issue by creativecontrol** [Chysn/O_C-HemisphereSuite#25]
Carpeggio, in Left Hemisphere, does not respond to any input. I have confirmed the triggers work for other modes; BootsNCats for instance. Carpeggio also does not respond to input on the Right Hemisphere but I think there may be an issue with my Digital 3 input on the hardware side.

**Comment by Chysn** [comment]
I'm unable to reproduce this. I tested Carpeggio in the left hemisphere and it works as expected. I can't explain why one applet would work and another would not, but if you already know you have at least one hardware issue with this O_C, I'd put that at a more likely cause.
