### ISSUE TITLE
Feature Request: Slew on/off via binary inputs

### ISSUE THREAD

**Issue by saiteron** [Chysn/O_C-HemisphereSuite#27]
would be awesome to be able to activate/deactivate slew with a gate sequencer for per-step glide! slew could default to on but if input is patched have gate high turn it on and gate low turn it off.

**Comment by Chysn** [comment]
I like that idea, and the digital inputs are available for Slew. I think I'd implement it as a "defeat" input, so that slew would not be activated when high. I'll certainly try it out and see how it works.

**Comment by Chysn** [comment]
Implemented in Hemisphere Suite 1.8
