### ISSUE TITLE
Possible to add Midi Clock to MidiIn?

### ISSUE THREAD

**Issue by CFenning** [Chysn/O_C-HemisphereSuite#35]
Would it be possible to add "Midi Clock" to the Midi-In applet? Would be really awesome to have this functionality outside of CaptainMidi. 

Thanks,
Charlie

**Comment by Chysn** [comment]
I think it's a great idea. I fear that there might not be enough memory left to do it. If this can't be done, it's only because I couldn't fit it in.

**Comment by CFenning** [comment]
Great! Look for it in a future update? Or…? I’m new to the Hemisphere firmware.

**Comment by CFenning** [comment]
> I think it's a great idea. I fear that there might not be enough memory left to do it. If this can't be done, it's only because I couldn't fit it in.

Any update on this?

**Comment by kurtjoy** [comment]
Id like the reverse...Midi clock out in the "midi out" app

**Comment by Chysn** [comment]
> Id like the reverse...Midi clock out in the "midi out" app

The Teensy 3.2 MIDI library does not have a way to construct a MIDI clock out message

**Comment by Chysn** [comment]
MIDI Clock is added to MIDI In as of Hemisphere Suite 1.8, for release on 12/21/2019
