### ISSUE TITLE
ShiftGate: Channel 2 goes dark?

### ISSUE THREAD

**Issue by clayton-grey** [Chysn/O_C-HemisphereSuite#36]
I was playing with ShiftGate this afternoon, and at one point I switched channel one from Gate to Trigger - or back? - I can't recall offhand, and channel 2 seemed to become stuck such that regardless of inputs the gate was seen as low so the pattern cleared out and no new outputs were generated. I tried reconnecting all cables with no luck. Resetting fixed, but it was in the middle of a practice set, which was unnerving. It's possible there was human error, but I don't think so. I've just integrated ShiftGate into my performance patch recently, so if the behavior repeats, I'll try to get a more accurate diagnosis.

**Comment by Chysn** [comment]
Thanks for your report.

When you say "resetting fixed," are you talking to power-cycling your system, or something else?

Are you able to provide a procedure for reproducing this behavior?

**Comment by Chysn** [comment]
I was unable to reproduce this while using ShiftGate. I suspect a transient hardware problem. I'll leave this open for a week or so, in case you reproduce it. If so, answer the following questions:

(1) Was ShiftGate in the left or right hemisphere?
(2) What was in the opposite hemisphere?
(3) When the condition begins, are you able to change to another applet?
(4) If so, does that applet have the same condition (that is, does its CV In 2 fail to function)?

**Comment by clayton-grey** [comment]
You're probably right on hardware. but I'll be working with it a lot right now, so I'll keep you posted.

**Comment by clayton-grey** [comment]
I've been using ShiftGate for at least 20 hours since this post with no issues, so this is probably safe to close. If it comes up again, I'll return!
