### ISSUE TITLE
Feature Inquiry: ShiftGate Normaling

### ISSUE THREAD

**Issue by clayton-grey** [Chysn/O_C-HemisphereSuite#38]
Firstly, since discovering ShiftGate, I love it. It's **tremendously** useful! 

Is it possible to internally normal the first channel's output to the second channel's input in code (A > C2, C > C4)? I'm doing this with stack cables now, and I'd love to save some cables and clutter. A pattern based on the other pattern is really useful to me, so mostly I'm curious if it's possible with the code and hardware as is (even if it's not something that goes into general release)?

**Comment by Chysn** [comment]
It's possible, of course. Personally, I don't think that using a patch cable is enough of a hardship to introduce a new interface element, but that's why this is an open-source project.

**Comment by Chysn** [comment]
I notice that you've contributed on development projects, so you can probably handle this. But if you'd like to contact me at my email address (from my GitHub profile), I'd be happy to give you any necessary guidance.
