### ISSUE TITLE
Enhancement..CV controlled crossfader

### ISSUE THREAD

**Issue by kurtjoy** [Chysn/O_C-HemisphereSuite#45]
Would be fantastic to get a reverse branches (ie 2 channels into one)  or a minimum a CV controlled crossfader for CV.

**Comment by Chysn** [comment]
Please see: https://github.com/Chysn/O_C-HemisphereSuite/wiki/Mixer:Balance

**Comment by Chysn** [comment]
Closing this, as the enhancement request is not possible within the current framework
