### ISSUE TITLE
Key Mixing UI for Quantizer

### ISSUE THREAD

**Issue by Jthrw** [Chysn/O_C-HemisphereSuite#50]
I'd like to suggest an optional variation on the quantizer user interface, based on the Camelot Wheel/Circle of Fifths, discussion [here](https://music.stackexchange.com/questions/42120/what-is-the-difference-between-the-circle-of-fifths-and-the-camelot-wheel)

The encoder would alow ideal navigation, rotation with the encoder switch moving between the inner and outer ring. I think it would be a great help when trying to jam with other people.

Thanks for your efforts, it's a wonderful firmware.

**Comment by Chysn** [comment]
That's a great idea. I think the simplest implementation would be changing the order of root notes in the setting (like going C, G, D, A, etc., instead of C, D, E, F, etc.). Probably not enough memory left to go much beyond that, but it's something to think about for future projects. Thanks!
