### ISSUE TITLE
Unlinked "A"SR

### ISSUE THREAD

**Issue by versipellis** [Chysn/O_C-HemisphereSuite#54]
Is it possible to run "A"SR in both hemispheres without being linked? I'd essentially like to be able to have two shifted inputs, and Hemisphere is the most efficient channels/hp there is if it's able to be run unlinked.

**Comment by Chysn** [comment]
If it detects "A"SR running in both hemispheres, they will always be linked. The reason for this is that there was only enough memory available for a single ring buffer. So when two copies of "A"SR are run, the second one is just sort of an "expander" with additional outputs for the one buffer.

**Comment by versipellis** [comment]
As a possible, as a suggestion in the future, to have two ring buffers with a shorter buffer length as a tradeoff?

**Comment by Chysn** [comment]
Yes, that's a good idea.

**Comment by versipellis** [comment]
Should I open that as a new issue for feature request?

**Comment by Chysn** [comment]
I'll re-open this one and add a the Enhancement label. But I have to be honest, I don't plan any further development of Hemisphere Suite at this time.

**Comment by Chysn** [comment]
I'm closing all outstanding issues with the "enhancement" label at this time, as no additional enhancements are planned.
