### ISSUE TITLE
Addition to SynthModes?

### ISSUE THREAD

**Issue by boourns** [Chysn/O_C-HemisphereSuite#55]
Hi @Chysn 

I run https://www.synthmodes.com and the Synth Modes app for iOS.  O&C Hemisphere is one of the most requested modules I have yet to add.  The documentation that powers the website and app is open-source and available here: https://github.com/boourns/synthmodes

I see the MIT license is on the documentation, so by license I would be okay to base my documentation on the wiki here, but I wanted to say hi and ask permission regardless.

Do you have any issue or preference with me adding documentation for Hemisphere based on the existing wiki and/or existing open source cheat sheets?

Thanks,
Tom

**Comment by Chysn** [comment]
Hi, Tom,

Sure, that sounds like a great idea. Thanks for asking!

Regards,
Jason
