### ISSUE TITLE
LowerRenz misbehaves

### ISSUE THREAD

**Issue by Chysn** [Chysn/O_C-HemisphereSuite#6]
Found a repeatable Bug which freezes the Module (1.4.B)

-Left side:
LowerRenz

-Right side:
LoFi Tape (for example)

-Save State

-Power down

-Power Up

-Select App Selection on the right side

-Turn right encoder CCW <- Important!
when You get to the LowerRenz app it freezes!

**Comment by Chysn** [comment]
Fixed in repo, not yet available in a hexfile

**Comment by Chysn** [comment]
Released in 1.4C

**Comment by benirose** [comment]
Sorry to comment on an old bug, but I'm experiencing a similar crashing issue in my build. Do you know what the root cause of this was?

**Comment by Chysn** [comment]
> Sorry to comment on an old bug, but I'm experiencing a similar crashing issue in my build. Do you know what the root cause of this was?

Sorry, I don't remember that far back. You may need to check out the commit.
