### ISSUE TITLE
Add SuperCollider link to wiki

### ISSUE THREAD

**Issue by madskjeldgaard** [Chysn/O_C-HemisphereSuite#60]
Hi! After some experimentation, I wrote a blog post on how to use Hemisphere/Captain MIDI with SuperCollider. If you feel like it, you can add it to the Captain MIDI part of the wiki

https://madskjeldgaard.dk/posts/hemisphere/

**Comment by Chysn** [comment]
Hey! Yeah, I'll be happy to put a link to your blog on the Captain MIDI
documentation. I'll do that this weekend. It looks like a neat project,
I've never heard of SuperCollider before.

--Jason
