### ISSUE TITLE
Augmenting Carpeggio into a full fledged app

### ISSUE THREAD

**Issue by dComposer** [Chysn/O_C-HemisphereSuite#66]
I'm absolutely in love with the Carpeggio applet and it seems like if it had access to all the CV/Trig inputs it could even be more special.

Inputs:
- an extra CV input could let you cv the transpose option so you could have a separate sequencer produce a bass line and carpeggio send out all the chord info for another middle or melodic voice
- same as above but CV-controllable chord changes
- a new trig input could let you switch between a list of predefined chords (ie, chord progression mode)
- you could trigger the start/stop for the sequencer

Outputs:
- perhaps there could be another option that lets you duplicate the output cv at a different octave/interval or perhaps even an option to make this second voice respond to the clock differently
- another option would be to include a faux gate/env output to accompany the note changes

Display:

- either keep the info how it currently is displayed on one panel and display the options on the other panel
- enlarge the matrix as large as possible so you could possibly fit some chord info inside each square

So many possibilities! What a cool applet!!

**Comment by Chysn** [comment]
Hey,

It's one of my favorites, too, and I agree that the 1/2 screen doesn't do it justice. I'd actually love to have a dedicated 20HP Carpeggio module. I'm on record as offering up the name "Carpeggio" to anybody that'd like to build such a thing.

But, as for this iteration of Hemisphere Suite, there's simply no room for anything else, so I'll have to close this issue as undone.

Take care!
--Jason
