### ISSUE TITLE
Problem uploading Hemisphere firmware, please help!

### ISSUE THREAD

**Issue by baunder** [Chysn/O_C-HemisphereSuite#67]
Hi, I'm very new to the whole Ornament & Crime world, and I just followed the steps for uploading Hemisphere firmware to my O&C.
Something went wrong, and now the module won't even start.
I got an Error while uploading via the Teensy app on OSX Mojave, and now I ended up with a "dead" module.
I can't even upload the 1.3 original firmware. The Module won't turn on.
Only the red LED next to the botton on the Teensy module.

I would really appreciate some help, as I'm a bit desperate (and ignorant) at the moment!

Thanks for your patience!
Cheers
Paul

**Comment by Chysn** [comment]
This system is for reporting software bugs, not hardware support. You might find better help in the forums on Muffwiggler or Lines.

Make sure that the Teensy is seated firmly in the module, that's about all I can think of.

Regards,
Jason
