### ISSUE TITLE
After Later Audio dials seem backwards when in the 180 degree mode

### ISSUE THREAD

**Issue by directgumby** [Chysn/O_C-HemisphereSuite#71]
I just picked up an After Later Audio O&C and installed the "HemisphereSuite_1_8_FLIP_180.hex" 
When using the device it feels like the rotation of the knobs feel backwards.

Repro:
1) Install HemisphereSuite_1_8_FLIP_180.hex onto an After Later Audio O&C
2) Press and hold the right knob to go into the menu
3) Turn the knob right (clockwise): 
  Note: The menu selection does not move and I would expect that it would advance the down through the menu.
4) Turn the know left (anti-clockwise):
  Note: you move down through the menu.

**Comment by Chysn** [comment]
This is not a defect, it's a calibration issue. Please calibrate the direction of the encoders per Ornament and Crime calibration instructions.
