### ISSUE TITLE
Scales 2x2x1 (two independent scales on 2 independent channels in one hemisphere)

### ISSUE THREAD

**Issue by directgumby** [Chysn/O_C-HemisphereSuite#72]
I am requesting a slight change (or new mode) to the scale mode in the following way:

1) Each channel can be independent for two scales
  Dig: 1/3 = clock to sample for  scale 1 
  Dig: 2/4 = clock to sample for scale 2 
  CV: 1/3 = CV1 in to scale with scale 1
  CV: 2/4 = CV2 in to scale with scale 2
  Out A: Scaled pitch 1
  Out B: Scaled pitch 2
  Button: toggles notes on and off for each scale for each channel 
2) (P2) an update to the UI that would include the ability to
  Have four scales, 2 per channel, and then have the first to stops in the UI have the ability to toggle between the two scales for each channel.  Note: It may be simpler to allow the user to select the scale from the saved scales in this UI.

Why am I requesting this?
I am using the O&C in a little 64hp case as primarily a two voice  system, and while I really like the hemispheres scale mode I can see a more efficient use by being able to use both channels for different scales, inputs, and outputs to different voices. 

Thank you for your consideration on this.

**Comment by Chysn** [comment]
I'll keep this on the feature request list; but realistically, Hemisphere Suite is feature-complete. There's no memory remaining for additional enhancements.

**Comment by Chysn** [comment]
I'm closing all outstanding issues with the "enhancement" label at this time, as no additional enhancements are planned.
