### ISSUE TITLE
OCP: VOR doesn't scale correctly

### ISSUE THREAD

**Issue by linusheck** [Chysn/O_C-HemisphereSuite#89]
Hi, I have an ornament and crime and loaded it with this hemisphere's hex file from Plum: https://www.plum-audio.com/firmwares
The VOR doesn't behave correctly (I think). Setting it as 0-10V scales it from 0-5V, setting it as -5 to 5V scales it as -5 to 0V and setting its as -3 to 7V scales it from -3 to 2V.. Is this the correct place to report this? And is this a known problem? Thanks!

**Comment by linusheck** [comment]
It seems like this is not the correct place to report this. Will refer to PlumAudio, closing this.

**Comment by linusheck** [comment]
Reopening this because I will fix it myself.

**Comment by linusheck** [comment]
Sharing some observations for anyone who's interested: I can't find the culprit yet. The whole VOR and DAC code seems to be 1:1 copied from the original O&C firmware, which works just fine. So it might have to do with how the apps actually use the DAC functions.

**Comment by linusheck** [comment]
Okay, it seems like this has to do with the actual values sent to the DAC from the apps.
If I adjust the `HEMISPHERE_MAX_CV` and `HEMISPHERE_CENTER_CV` like this:
```
#elif defined(VOR)
VBiasManager *vbias_m = vbias_m->get();
int32_t getMaxCV() {
    switch (vbias_m->bias_state) {
        case VBiasManager::UNI:
            return 15360;
        case VBiasManager::ASYM:
            return 10752;
        case VBiasManager::BI:
            return 7680;
    }
    return 0;
}
knt32_t getCenterCV() {
    switch (vbias_m->bias_state) {
        case VBiasManager::UNI:
            return 7680;
        case VBiasManager::ASYM:
            return 3072;
        case VBiasManager::BI:
            return 0;
    }
    return 0;
}
#define HEMISPHERE_MAX_CV getMaxCV()
#define HEMISPHERE_CENTER_CV getCenterCV()

#else

```
then Voltages delivers the correct voltages for 0-10V and -3-7V (I made some mistake at -5-5V, not sure), when set to the correct ranges.

**Comment by linusheck** [comment]
This is of course not a good idea to actually do, I think it's fine at first that the apps just think -5 to 5V is currently active. But this is still some progress for me.

**Comment by linusheck** [comment]
There we go, I found the fix.

**Comment by linusheck** [comment]
Repurposing this issue for "Calibration messed up".

**Comment by Chysn** [comment]
I'm closing this, as I don't plan to do anything further with VOR

**Comment by linusheck** [comment]
good call :)
