### ISSUE TITLE
Feature Request: Visual Feedback of Clock Divider Multiplier pulses

### ISSUE THREAD

**Issue by Airell** [Chysn/O_C-HemisphereSuite#94]
There is no visual feedback on when a pulse/clock has been input/processed and been output-ed.
I was working with an already 1/12th div clock, but I couldn't see what was going on.
Showing a simple blinking dot or letter (T), (P), (D)iv, (M)ult can do the trick.

**Comment by Chysn** [comment]
I'm closing all outstanding issues with the "enhancement" label at this time, as no additional enhancements are planned.
