### ISSUE TITLE
Feature Request: Slower LFO

### ISSUE THREAD

**Issue by nelsonmilum** [Chysn/O_C-HemisphereSuite#95]
The frequency range on the LFO applets Skewed LFO & Vector LFO would be really nice if I could get it in the 60 seconds to several minutes range. In the vein of Quadraturia in vslow or lazy mode

**Comment by ghost** [comment]
+1 on this..

**Comment by MrDorianJames** [comment]
Definitely agree.  Also clock division to slow it down to sync input

**Comment by Chysn** [comment]
I'm closing all outstanding issues with the "enhancement" label at this time, as no additional enhancements are planned.
