### ISSUE TITLE
Add time indicator to ADSR EG

### ISSUE THREAD

**Issue by armandhammer** [Chysn/O_C-HemisphereSuite#97]
It would be nice to see the segment times displayed on screen (while editing) for the ADSR EG like it is for the AR EG.

**Comment by Chysn** [comment]
I'm closing all outstanding issues with the "enhancement" label at this time, due to no additional enhancements planned.

**Comment by charonme** [comment]
like this? https://github.com/Chysn/O_C-HemisphereSuite/pull/51
