### ISSUE TITLE
Bug: Darkest Timeline crashes if Root note set too high

### ISSUE THREAD

**Issue by jddinneen** [Chysn/O_C-HemisphereSuite#98]
Hello and thank you for your work. I have found that, in the Darkest Timeline app, changing the root note past the highest value crashes the module (i.e. inoperative, requiring power off to reset). The cause wasn't obvious from a glance at the code but I'm otherwise happy to help troubleshoot.
-JDD

**Comment by nelsonmilum** [comment]
+1 also happens here.

**Comment by Chysn** [comment]
Pull request approved for 1.9. Thanks!

**Comment by evgazloy** [comment]
Glad to help. Thank you for your work!
