### ISSUE TITLE
Feature request: random playback in CV Recorder / Darkest Timeline

### ISSUE THREAD

**Issue by jddinneen** [Chysn/O_C-HemisphereSuite#99]
I would find it super useful if CV Recorder and/or Darkest Timeline had different playback modes for the sequence e.g. 'random' and backwards. If a random walk (e.g. w/ length equal to the whole sequence) could be repeated (locked/unlocked), that would be super and add a Marbles-like feature. Maybe some code from Marbles can be re-used? Happy to help in any way.
Thank you, 
-JDD

**Comment by Chysn** [comment]
I'm closing all outstanding issues with the "enhancement" label at this time, due to no additional enhancements planned.
